version: "3"

services:
  server:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/server
    command: >
      # sh -c "python doctor_threaded.py"
      sh -c "python test_doctor_threaded.py"