version: "3"

services:
  server:
    build:
      context: .
    ports:
      - "5050:5050"
    volumes:
      - .:/server
    command: >
      sh -c "python doctor_threaded.py"
      # sh -c "python test_doctor.py"